"""Initial migration.

Revision ID: 059345070ec7
Revises: d279763cf646
Create Date: 2024-07-25 10:15:50.156632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059345070ec7'
down_revision = 'd279763cf646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_user_movie_list_movie_id_list_movies', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_movie_list_list_id_list_movies'), 'list_movies', ['list_id'], ['movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_list', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_movie_list_list_id_list_movies'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_movie_list_movie_id_list_movies', 'list_movies', ['movie_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
